pipeline {
    agent any
    stages {
        stage('Install') {
            steps {
                sh "echo 'Install dependancies'"
            }
            }
        }
        stage('Run_tests') {
            steps {
                sh "echo 'TEsts passed'"
            }
        }
        stage ('Build') {
            steps {
                sh "echo 'Built'"
            }
        }
    }
}
